POST http://localhost:3000/books
content-type: application/json

{
    "name": "name",
    "description": "description"
}

###
POST http://localhost:3000/books/read-files
content-type: application/json

{
    "pathname": "../books.controller.js"
}

###
GET http://localhost:3000/books

###
GET http://localhost:3000/books/redirect?url=http://google.com

###
GET http://localhost:3000/books/title/title

###
GET http://localhost:3000/books/name/name

###
GET http://localhost:3000/books/1

###
PATCH http://localhost:3000/books/1
content-type: application/json

{
    "name": "updated name",
    "description": "updated description"
}

###
DELETE http://localhost:3000/books/1
